"""add reset-token

Revision ID: 11978b5c645a
Revises: cb4415365e84
Create Date: 2023-07-09 17:17:39.145438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11978b5c645a'
down_revision = 'cb4415365e84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
